'use client'

import { useState } from 'react'
import { ArrowRight, Check, Menu, MessageCircle, ShieldCheck, Star, X } from 'lucide-react'

const wa = 'https://wa.me/447476605409?text=Hello%20Sky%20Global%20Travels%2C%20I%27d%20like%20a%20travel%20quote.'
const destinations = [
  ['Marrakech', 'Morocco', 'marrakech.jpg', 'Souks · riads · culture', '£399'],
  ['Dubai', 'UAE', 'dubai.jpg', 'Luxury · shopping · desert', '£530'],
  ['Cairo', 'Egypt', 'egypt.jpg', 'Pyramids · Nile · history', '£289'],
  ['Bali', 'Indonesia', 'bali.jpg', 'Temples · beaches · nature', '£450'],
  ['Thailand', 'Thailand', 'thailand.jpg', 'Islands · food · culture', '£430'],
  ['Istanbul', 'Türkiye', 'turkey.jpg', 'History · mosques · Bosphorus', '£299'],
  ['Antalya', 'Türkiye', 'turkey.jpg', 'Resorts · coast · sunshine', '£379'],
  ['Maldives', 'Indian Ocean', 'maldives.jpg', 'Luxury · lagoons · honeymoons', '£899'],
]
const deals = [
  ['Hurghada', 'Egypt · Red Sea', 'egypt.jpg', 'Winter sun', 'Beach resorts, warm weather and Red Sea adventures.', '£339'],
  ['Sharm El Sheikh', 'Egypt · Red Sea', 'sharm.jpg', 'Beach escape', 'Clear water, coral reefs and relaxed all-inclusive stays.', '£359'],
  ['Canary Islands', 'Spain · Atlantic', 'canary.jpg', 'Winter getaway', 'Sun, beaches and easy-going island holidays.', '£480'],
]

export default function Home() {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [sent, setSent] = useState(false)
  return <main>
    <header className="site-header"><div className="container nav"><a href="#top" className="brand"><img src="/sky-global-travels-logo.jpg" alt="Sky Global Travels logo" /></a><nav className="nav-links"><a href="#deals">Deals</a><a href="#destinations">Destinations</a><a href="#umrah">Umrah</a><a href="#about">Why us</a><a href="#contact">Contact</a></nav><div className="nav-actions"><a className="nav-book" href={wa}>Book on WhatsApp</a><button className="menu-btn" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div></div>{open && <nav className="mobile-menu">{['deals','destinations','umrah','about','contact'].map(item => <a key={item} href={`#${item}`} onClick={() => setOpen(false)}>{item[0].toUpperCase() + item.slice(1)}</a>)}</nav>}</header>
    <section className="hero" id="top"><div className="container hero-grid"><div><div className="eyebrow"><span /> UK travel specialists · Personal service</div><h1>Travel further. <em>Feel looked after.</em></h1><p>Flights, holidays and Umrah journeys from the UK — with straightforward advice, clear options and a real person available on WhatsApp.</p><div className="hero-buttons"><a className="btn primary" href={wa}>Get a free quote <ArrowRight /></a><a className="btn light" href="#destinations">Explore destinations</a></div><p className="email-line">Book via email: <a href="mailto:skygtravels1@gmail.com">skygtravels1@gmail.com</a></p><div className="hero-proof"><div className="atol"><ShieldCheck /><span><b>ATOL Protected</b><small>Financial protection for eligible package holidays</small></span></div><div><b>50+</b><small>destinations</small></div><div><b>UK based</b><small>personal support</small></div></div></div><div className="hero-visual"><img src="/turkey.jpg" alt="Mediterranean coastline in Antalya" /><div className="floating"><Check /> Personal booking support</div><div className="image-label"><small>Featured escape</small><b>Antalya, Türkiye</b></div></div></div></section>
    <div className="trust"><div className="container trust-grid">{[['UK based','London registered business'],['ATOL Protected','Eligible package holidays'],['Clear enquiries','Talk to a real person'],['24/7 support','Help before and during travel']].map(([title, copy]) => <div key={title}><span>✓</span><b>{title}</b><small>{copy}</small></div>)}</div></div>
    <section className="cream" id="deals"><div className="container"><div className="section-top"><div><label>Popular right now</label><h2>Holiday ideas worth asking about</h2></div><p>Prices are indicative “from” prices and depend on dates, availability, hotel and flight options. Contact us for a live quote.</p></div><div className="deal-grid">{deals.map(([name, location, image, badge, copy, price]) => <article className="deal-card" key={name}><div className="deal-img"><img src={`/${image}`} alt={name} /><span>{badge}</span></div><div className="deal-body"><label>{location}</label><h3>{name}</h3><p>{copy}</p><div className="price"><b>From {price}</b> <small>pp</small><a href={wa}>Enquire <ArrowRight /></a></div></div></article>)}</div></div></section>
    <section id="destinations"><div className="container"><div className="section-top"><div><label>Explore</label><h2>Beautiful places. One simple starting point.</h2></div><p>Tap a destination to start an enquiry. We can help with flights, hotels, transfers and package options.</p></div><div className="destination-grid">{destinations.map(([name, country, image, detail, price]) => <a className="destination" href={wa} key={name}><img src={`/${image}`} alt={name} /><div><label>{country}</label><h3>{name}</h3><p>{detail}</p><b>Packages from {price}pp</b></div></a>)}</div></div></section>
    <section className="umrah" id="umrah"><div className="container umrah-grid"><img src="/makkah.jpg" alt="Makkah mosque" /><div><label>Spiritual journeys</label><h2>Umrah, thoughtfully arranged.</h2><p>From flights and hotels to transfers and guidance, we help make your journey to Makkah and Madinah feel simple from the first conversation.</p><ul><li>Packages from London and across the UK</li><li>Hotel and flight options to suit your needs</li><li>Personal support before and during travel</li><li>Clear, honest advice at every step</li></ul><a className="btn primary" href={wa}>Ask about Umrah <ArrowRight /></a></div></div></section>
    <section id="about"><div className="container why-grid"><div><label>Why Sky Global Travels</label><h2>A better way to book your next journey.</h2><p className="muted">Travel can feel complicated. Our role is to make it clearer, more personal and easier to feel confident about.</p><div className="reasons"><div className="reason"><Check /><span><b>Personal service</b><small>Speak to someone who listens to what you actually need.</small></span></div><div className="reason"><ShieldCheck /><span><b>Clear options</b><small>Straightforward quotes with no confusing surprises.</small></span></div><div className="reason"><Star /><span><b>Trusted support</b><small>Help before you go, while you travel and when you return.</small></span></div></div></div><img className="why-image" src="/malaysia.jpg" alt="Tropical travel destination" /></div></section>
    <section className="reviews" id="reviews"><div className="container"><div className="section-top"><div><label>Customer stories</label><h2>Travel with confidence.</h2></div><p>Real support, thoughtful planning and journeys our customers remember.</p></div><div className="review-grid">{[['Excellent service from start to finish. They found us exactly what we needed.','Aisha M.'],['Clear, friendly and genuinely helpful. I would definitely book through them again.','Hassan R.'],['Our Umrah arrangements felt completely stress-free. Thank you.','Nadia K.']].map(([quote, author]) => <blockquote key={author}><div className="stars">★★★★★</div><p>“{quote}”</p><small><b>{author}</b> · UK</small></blockquote>)}</div></div></section>
    <section className="contact" id="contact"><div className="container contact-grid"><div><label>Start planning</label><h2>Tell us where you want to go.</h2><p className="muted">Share a few details and we will come back with options that fit your dates, budget and travel style.</p><div className="contact-details"><a href="mailto:skygtravels1@gmail.com"><small>Email</small><b>skygtravels1@gmail.com</b></a><a href={wa}><small>WhatsApp</small><b>+44 7476 605409</b></a></div></div><form className="quote-form" onSubmit={event => { event.preventDefault(); setSent(true) }}><div className="form-grid"><label>Name<input required placeholder="Your name" /></label><label>Phone<input required placeholder="Your number" /></label><label>Destination<input placeholder="Where would you like to go?" /></label><label>Travel dates<input placeholder="Flexible is fine" /></label><label className="full">Tell us more<textarea placeholder="Number of travellers, budget or anything else..." /></label></div><button className="btn primary" type="submit">Send enquiry <ArrowRight /></button>{sent && <small className="success">Thanks — we’ll be in touch shortly.</small>}</form></div></section>
    <footer><div className="container footer-top"><b>Sky Global Travels</b><nav><a href="#deals">Deals</a><a href="#destinations">Destinations</a><a href="#contact">Contact</a></nav></div><div className="container footer-bottom"><span>© 2026 Sky Global Travels. All rights reserved.</span><span>London registered travel specialists · <a href="mailto:skygtravels1@gmail.com">skygtravels1@gmail.com</a></span></div></footer><a className="whatsapp" href={wa} aria-label="Chat on WhatsApp"><MessageCircle /></a><div className="mobile-bar"><a href={wa}>WhatsApp</a><a href="#contact">Get a quote</a></div>
  </main>
}

